### ISSUE TITLE
Feature Request - Possible to put in a list of quest ids for the addon to automatically abandon

### ISSUE THREAD

**Issue by Shamatix** [MotherGinger/RecklessAbandon-Classic#11]
I would love for there to be a feature to automatically abandon quests based on a list of quest ID I can put in.

So if I have a list of 30+ quest Ids I dont want to complete, I want the addon to automatically abandon those quests if I pick em up by a mistake.

Best regards

PS: Also tried to msg you on reddit:P

**Comment by MotherGinger** [comment]
Hey there thanks for the feature request!

This is a great idea! I'd like to implement this in the next release and give you credit, what is your in-game name, server, and class? Or if you have another handle you'd like to go by that would work as well!

P.S. Sorry about missing your message, I've just pinged you back just in case you don't see this right away
